---
title: Projects
toc: true
toc-title: Contents
toc-location: left
---

## MPSA 2025 Paper

This paper will argue that many variables in dyadic regression could be improved in a reasonably parsimonious way to better measure the variation in the magnitude of network effects. This paper will focus on Alliance Networks in a continuation to the work of Dr. Leeds and Dr. Johnson. The key to this first paper will be in demonstrating the available variation in alliance integration which the established theory literature posits should alter the effect of being an alliance member. Since the paper is not complete, below is an interactive network map which is the foundation for the paper.

<div style="overflow: hidden; position: relative; width: 100%; height: 100%;">
  <iframe src="https://jonathan-durbin.shinyapps.io/AllianceNetworkMaps/" 
          style="border: none; width: 100%; height: 1000px;"
          allowfullscreen>
  </iframe>
</div>

----

## BARKS 2023

In Fall 2023 and Spring 2024, I worked with Dr. Kuehl, Eman Alahmadi, and Oliver Myers on the Behaviors, Attitudes, Resources, and Knowledge of Sustainability Survey (BARKS Survey) available [here](https://www.niu.edu/sustainability/_files/2023-barks-report.docx). The survey was conducted in September and October 2023 with analysis conducted in November and September and the writing of the report done in December and January. Dr. Kuehl and Eman Alahmadi have gone on to use resulting survey experiment data in a paper which has hit the R&R stage. Oliver Myers wrote the bulk of the survey and report with me doing the copy editing. I created the graphs for the report as well as created the commute section of questions. This data was used by me in a term paper and by the Office of Sustainability in its greenhouse gas inventory and its Sustainability, Tracking, Assessment, and Rating System (STARS) report.