---
title: "index"
format: html
---

We begin the session by tying Balbaroy up and heading out to find Various. Once the commanders were occupied by us, the assault of the fort did not take very long. Making our way through the fort we see Dauss knights laying down their arms surrendering. After a brief conversation with Various we loot Eric and Tywin. From the parapets we see a large force on the edge of the forest, it turns around and heads out. Various says he is staying here to rebuild, he lends us Guntz as an escort and we head back to Norgrain with Balbaroy.

On the way back we talk to Balbaroy a little bit, he is apparently from Ratheious, he expects to be killed. Some time into our trip we hear someone say "that's not right" then a very loud pop. We decide to leave Guntz with Balbaroy and go towards the sound, once we are there all we find is a pack, a book, and a messed up spell circle. The book is titled "Spells for Dummies" and Selscior can tell fairly easily that none of the spells in it would function correctly.

We continue on our way and have a brief conversation with Guntz. He is impressed that we have been able to find and make it through several Warden tombs. Apparently he knows the location of one to the north but was never able to open it. We decide that next Warden tomb will be that one and we will bring Guntz with us.

We are in the farms surrounding Norgrain when we stop to pick some hexseed. Not far away from where we stop we see a section of blighted grain. We find the closest farmers and suggest that they harvest as soon as possible and let the others know.

Planning in Norgrain

When we make it back we are able to find Castillo, Brauchuss is unavailable at the moment. We find out that Oswald has his spying ring up and running. Roland has a brief exchange with Castillo where he says that ambition killed his reign. He also adds that it the other lords were not wrong to seek his removal. Castillo decides it is well past time that we get properly rewarded by Norgrain. In conversation he proposes a few properties and floats the idea of rebuilding Hamiltown, he also upgrades our cart giving us a banner of Norgrain as well. After some discussion we decide that we would love to rebuild Hamiltown; however, winter is on its way so we should wait a little bit. We conclude that we will take a property in Norgrain.

The party breaks up at this point to get some individual stuff out of the way. Selscior and Dawn go to the library to sell the Hearthstone, it is worth 250 gold pieces. Selscior is also offered acceptence into the college, first he pays Castillo a visit asking about the joining the spy ring. He is directed to meet with Oswald and after going to Oswald's office he joins the spy ring. He opts not to let any of us know.

Roland, Ryean, and Lutin go to the brawling pit for some hand to hand pvp, very fun. In the last round Ryean faces an npc and they go back and forth grappling each other, quite funny. At last we meet back up and select a few quests to do in the coming days. We talk to Casandra, a centaur that is headed out to Fort Dauss to help train the garrison, we help her pack. Finally we head to our house to figure out sleeping arrangements. Dawn in the attic, Ryean and Lutin get rooms, then Selscior and Roland get places in the living room.

Butch Hits the Fan

Lutin talks to Butch who shows him the strings tying us to the gods. Lutin slices his own string, separating himself from his deity patrons. He then heads downstairs and does the same for Selscior then Roland. Each have a brief interaction with Butch before accepting his ultimatum. He ends with Ryean who has an extended conversation with Butch before accepting the deal.

Dawn is pulled into a dream and sees the Pantheon of Ostergaia in an uproar. The gods decide to execute Myrtle for her interference in the game. Dawnsbloom starts to react when Myrtle teleports her away. The session ends with Myrtle being executed.