---
title: "index"
format: html
---

We arrive in Norgrain fully rested and head to the general store manager. He gives us 350 gold pieces in all. We then head back to the house to investigate the pie Rose made for us. The pie has eight slices, when administered they will take a downed character up to half health. We decide to go to sleep, during the night Dawnsbloom misty steps into Lutin's room and drops onto his stomach then misty steps away. We then wake up to Dawn making an absolutely exquisite breakfast. She critted for stealth when messing with Lutin then again on breakfast, 10/10 bit.

During breakfast we hear a knocking at the door which Dawnsbloom answers. It is Father Varilio, she promptly closes the door and calls for Lutin who ran upstairs and is diving out the window. Ryean goes to the door and talks to Father Varilio, it would seem Varilio just missed Lutin. Varilio has gotten some more powerful worshipers together to retry the exorcism. If Lutin continues on the path he may be branded a heretic and if we help in it would extend to us.

With that somewhat ominous conversation out of the way we head to the Healer Shanty to grab Rose. When we ask for her there is some consternation but she insists that her mission will allow her to be considerably more useful. She has heard of an Ursagul terrorizing the country side, in the lair of the beast should be some special mushrooms. Before we leave a make a quick stop at Tristrums to get the sheath altered. Apparently Lord Brauchuss is going west for negotiations and needs fine clothes, but he will make room for us.

A Bear of a Job

We head out towards Merryduke Farm and find the trail of the Ursagul. The trail leads to the north west, Merryduke manages most of the farmland surrounding Norgrain. We find them in their barn pouring over maps, almanacs, and botany books trying to figure what weather resistant crops to grow. They don't have much information mainly they have a wolf issue and we should talk to their friend Furgus. On the way to the house we find a geyser that has been turned into a sauna and choose to relax for a bit. When we get to his house we see a dragon born wearing a straw hat in a rocking chair. It is somewhat clear he has been trying to keep an eye out but fell asleep.

After waking up, he leads us down the trail of ruin to get to the . We all circle up and start trying to help Ryan work on his rizz. While we are doing this, Rose continued on and we don't see her. So we spend the next few minutes running around loony-tunes style until we get everyone back together. When we finally make it to his farm we see three of his seven bee huts have been destroyed.

We continue on our way and find the Ursagul fairly quickly. A turn or two into the combat five wolves appear, one of them got two crits on Dawn... ouch! Lutin does the killing blow on the Ursagul to which Rose freaks out because it would have been easier to follow it to its lair. Lutin tracks the trail back to the cave which takes about an hour. Selscior also gets the raven back and walks away from us (it has a letter and ten gold). Rose is able to carefully retrieve the mushrooms and we head back to Norgrain.

Danger Will Robinson

On the way back to the wagon we see seven people traveling parallel to us. We intersect them and as it turns out it is Boar Mask guy and six of his pals. He tells his friends to finish their job and they depart. We talk to him for a while. We find out that he only became a champion during the raid on Hamiltown. He also keeps saying "she should be here soon", the "she" as it turns out is the monk from the last game. She appears and it would see she and Qolbis have a score to settle with Lutin