---
title: "index"
format: html
---

Lutin and Ryan have a private conversation. Dawn, Ryean, Selscior, and Roland all have a private meeting and decide to plan to have a plan. Ryan talks to Zephene, apparently the gods are merely of this continent, other continents, worlds, etc... have their own gods. Dawn has a meeting with Myrtle, apparently she is going to be on a vacation of sorts in a bit, Dawn is also told she had an entire other life forgotten from before she volunteered to help Myrtle. Lutin also has a discussion with the new aspect of Butch, which now does bleeding damage.

When we all wake up after the very busy night, we head to Tristrum who just finished Selsciors ring, which is now one heck of an item, and Lutin receives his clothes. We head to the church and see Varilio talking to Chalbert, the crusading son of Novascoshek who is apparently headed back south. Lutin wants to see if Varilio can perform an exorcism to separate Lutin from Butch. It takes many priests but they are succeeding when Lutin intentionally destroys the ritual circle and Butch blasts them all, knocking them out. Roland goes to a shop to grab ten gold pieces worth of herbs to give Selscior to recast Find Familiar.

The Siege

Once we wrap up everything in town we head out to the siege. On our way we run into a centaur in full gear, apparently he is from the Faltenlands, Selscior points him in the very general direction. We then run into a group of witch hunters, people take the spell casting registry very seriously. Finally, before arriving we find some hexseed.

Once at the siege we talk to Various, either we can be part of the main force, or sneak our way in and take out the commanders. With the aid of four ghillie mantels that increase our stealth a great deal, we decide to sneak in. We also finally decide to call upon Qolbis for that storm we have been holding onto.

To sneak in we need to circle the fort and enter a trap door that is in the middle of the clearing surrounding the fort. We use our mantels to sneak to the door and not get detected by two archers. Roland takes a hit or two when one of them spots something is off. We descend into the tunnel and make our way into the jail where we break prisoners out and gear Guntz. Next we head to the smithy where we find more locked up people. It would seem Ryean's brother joined them and left for Ratheious. We then have a very exciting fight. I played Roland and Guntz, we had the opportunity to dodge lightning strikes, and they were generally powerful.

We ended the session with Tywin (swordmaster) killed by us, Eric (archer) dead, and a defeated Balbaroy.