---
title: "index"
format: html
---

A rock 'n' morning

Lutin is awoken bright and early by the owner of the Rock 'n' Stone banging on the posts of the inn. Ryean does not wake up and is tossed out of the inn. We get our bearings, we are in Simpletis, a reasonably sized town with two inns, a library, a general store, an armory, apple seller, pawn broker, and a hunters shed. As we make our way through the town we get a general eerie feeling, the southern half is abandoned.

We make our way to the library. The librarian is extraordinarily tired and over worked, he's been working over time for the mayor. As it turns out this scholar can read primordial, we hand him some of our material for him to translate, he also takes the wizards tome. Dawn also starts learning primordial with his help and Selscior starts doing some research on the town. We ask the librarian about the state of the town which he had not been aware of.

A big stick

The rest of us head to the Protection Emporium. While digging around we ask about any swords, apparently the owner had just sold their best sword. Months ago the former Lord of Norgrain, Castillo, bought a replica of an ancient sword, it was silver with gemstone, and had a worn inscription. The shop owner bought this sword from a merchant in the east.

With that information and a new weapon for Ryean we then went to the hunting shed. We learn from the owner that no one has been hunting because of bandits. Ryean is able to get a heavy crossbow, he must do a sponsor read with every shot, and Lutin gets a few bear traps.

Not softly spoken

With a newly armed group we marched back to the library to pick up Dawnsbloom and Selscior. Selscior informs us that the Lord of Norgrain to the north, Brauchuss, and the Lord of Ledenfowl have started to clash. Simpletis is on the border of the two kingdoms and as such received a partial garrison from both; however, the both of them withdrew their soldiers creating a power vacuum.

Bandits started robbing merchants on their way to Simpletis, set up camp in the woods, and started abducting people from town. This has created somewhat of a crisis for the Mayor whose only option was to contract with a mercenary company. The three circus tents are a bit of an unknown, they just showed up one day and sent out tickets.

Now that our concerns have been raised we head for the mayors manor. Outside of the manor is a quest board covered with postings for bandits and a monster to the south terrorizing a farm. When enter the manor to discuss the bounties and issues with the mayor. He is an elderly bronze dragonborn, a gentle father and grandfather that cares for the town. We are able to obtain a wagon and a team of animals. We decide to head out to the south and strike out at the monster, whatever it may be.

Along our path was a group of people, Selscior got a natural 20 on stealth and moved into investigate the people. It is a group of orcs, half-orcs, and dwarves half exhausted to death, they had been running for two days from Hamiltown. We tell Yurnack, a dwarf that used to farm for Novascoshek's estate, the direction of Simpletis.

The bigger stick

We continue on our way until we run into two people tending a field, while they grow plants like other farms, they mostly make honey. The main building is a massive bee hive that has been broken into by the monster. We start fortifying the position, laying out the bear traps, and taking places to ambush the mighty beast. Roland hides in the building behind the hive boxes, Selscior makes a very convincing scarecrow, Dawn takes up the shed roof, Lutin and Ryean hide off to the side of the building. We aren't waiting too long before the behemoth appears.

The beast steps on a trap and shakes it off before continuing its lurching walk towards the building. The battle is fierce, it leaves in its wake a trail of difficult terrain making it hazardous to move. It collapses half the building managing to knock Dawnsbloom down. Even with Ryean, Roland, and Lutin all striking savagely at the beast it manages to hold its ground. Every strike was somewhat muted by the fact the unnatural bear had a thick oil coating its fur which would clot its wounds.

Finally we are able to take the monster down, only for it is dissolve into nothing leaving behind a tooth and Gauntlets of the Ursagul. Ryean picks them up and attunes to them up and we ask to sleep the night at the farm house. In the night we have a shared dream, Myrtle, Goldmir, and Qolbis inform us that we will soon face a champion of Esara, the Goddess of Love. We wake up and head to town as quickly as possible.

Shot through the heart

When we get to town we see all the doors are shut tight, no one is outside, when we arrive at the manor we see the door is slightly ajar. We push our way in to see the mayor and his son pouring over a desk of papers. Many people have gone missing, while we were away the circus opened, people went in but no one has left. We resolve to go to the circus, find out what is going on, and save the mayors grandson.

We approach the circus tent and see a sign that says "Tickets for Administration", as we step through our tickets burn up in our hands. We hear Myrtle tell us "Set the board" and we enter the hallway entrance, we start walking forward. We seem to be walking further and further without getting any closer to the room. Ryean turns around and starts walking backwards, hits a figure, turns around and sees an elf with a pair of massive golden wings "Welcome to the games."