---
title: "index"
format: html
---

We start the session very calmly by rolling initiative. We all roll really high... Bailgar and Sarah still win the intiative. Sarah focuses on Lutin at the beginning and none of us step in to help, focusing on Bailgar. Lutin is about to drop when we start fighting Sarah. The combat was quite long, with characters going down, rolling a few death saves, getting back up, very intense and lots of fun. We end the combat with Sarah dead (killed by Sarah) and Bailgar tied up, we talk to him for a bit before leaving.

Travel

After getting our cart while heading to Fergus a pack of wolves skirts around us. They start threatening us before Jerma jumps out in front and pushes them on. One of the wolves stays hangs back a bit longer before running after the others. After talking to Fergus we start off to Maryduke Farms. While headed there we meet a merchant caravan with a detachment of knights, we start talking to Nicholas who gives us five gold each.

Norgrain

Once in Norgrain we collect my plate armor, Roland's natural AC of 21. We then stop by Tristrum to get the modified sheath and Dawns' outfit. When we are back in our house Selscior gets out a letter from his mother (it's not from is mother) asking us to go to Kleptins Keep, it seems like we will. Ryean has a very personal conversation with Goldmyre, Dawnsbloom talks to Myrtle who tricked all the gods into thinking she was dead. In all, it was a good session of D&D which gave everyone plenty to think about and plan over spring break.