---
title: "index"
format: html
---

We wake up three weeks later, Roland gets awake first and uses his energy healing Lutin and Dawnsbloom. We start wondering the halls of the healers tent until we find Ryean. We talk to Rose, she is a champion, Ryean is not happy with this development but glad she feels good that she can aid people through healing. We go to a shed and retrieve our gear when a dozen guards surround the shed.

We are pulled before the court of Lord Brauchuss and see his entire court, they read the letter aloud, clearing our names. With that done we head off to become registered/known mages, Selscior (still asleep) acquires a pass into the library since his is academic magic.

We then go shopping, buying three dozen mystery potions that make Ryean and Lutin go a little loopy. Rose informs us she needs more herbs to do her job and we go to the shanty town, mostly people from Hamiltown/Outskirts. In the town center we saw a man in the stocks, we find his friend Gesik going door to door. He expresses is understandable displeasure with the situation he is now in, they are only allowed to be in the slums or at the church.

We decide we will try to help the people here at least a little and spend the next day making a copious amount of bread. It turns out the town used to try and help those in need, but because of a necessary increase in funding for other things and the sharp increase of those in need, they couldn't continue to aid people. We are able to make enough food to get everyone to last about a week on meager rations.

We got a summons from the former lord, Castillo, so once we were done delivering the food we headed over. We were stopped and reprimanded by a guard for not having a torch, we are too late anyways, the gate has been closed for the night, we decide to go to the inn and rest.

In the morning we go to meet with Castillo, as it turns out Castillo is currently talking to Lord Brauchuss, the degree to which they do not see eye to eye is audible. We head to the Spy Master's room, we get there as Myra, the head diplomat of the court, it leaving, it would seem she has, maybe, unintentionally taking over his job. We hand over the letter from Novascosheks chambers and the stamp, he is glad to see we had the restraint to not open it.

It is clear in our discussion that he is not pleased with the leadership of Norgrain or Borgeniss. Roland starts digging for information about Castillo. It turns out he has two brothers, one of them died, the other became a monk, had a family and his son, Brauchuss became the lord. When pushed the Spy Master claims he is under a strict oath not to discuss the removal of Castillo or installment of Brauchuss.

We head to Castillo's room as Brauchuss exits, he demands we bow to him, we do so. It would appear the former lord was something of a hunter with his office walls lined with game trophies and floor covered with skins. He is also very busy for a former lord, after a rather brief conversation we are on our way to Fort Dauss.

We stop to talk to Rose whom we found out is also a champion in this Game of the Gods, Ryean is not thrilled, she asks us to collect some herbs for the upcoming siege.

On our way north to Fort Dauss we notice that some of the scarecrows shift every once in a while, we approach two. We talk to them, turns out these scarecrows are respectable mimics just trying to make a living.

We also stop everyone once in a while to pick herbs until we reach the forest. We start to hear in the distance quite whelps and whimpering, it gradually gets louder, we decide to investigate. It turns out to be a wolf pup entangled in vines, Lutin carefully unties the pup and heals it, we also get some bellalichen.

We finally get to Fort Dauss, Sir Balbaroy is on the parapets and calls out to us, says he's sending a detachment of cavalry to us. The entire party feels something is off, Roland crits and senses he is being insincere. We call out to him that the cavalry really aren't necessary and he calls them off and while they are turning we also turn heading away from Fort Dauss as fast as possible.

After a very fun chase sequence where we lit stuff on fire, threw out boxes and barrels, conjured fog, etc. we escape and force march through the night back to Norgrain. It would seem Balbaroy is working with Ratheious and Ledenfoul. Upon discussion Verious decides we will actively seek to be less suspicious of us and says we should head to the druid Mae wrote of.