---
title: "index"
format: html
---

In this wild garden Dawn starts to wonder, the rest of the party follows, we find an ent, Pinochle. In conversation Pinochle states there is something off about the new goods. Apparently Dawnsbloom is the only fairy in existence and the first in 500 years. Apparently Laxaldir, the ents, and fairies were the first beings in existence. When Myrtle and Ieyagi came into existence they merely became the care givers of nature and plants which predated them.

Within this wild garden was once a great tree, only three seeds from which exist, Pinochle gives us one to aid the people of Norgrain. She also informs us of a petrified ent within Bleakwoods, once of the single oldest entities in existence. We also find out that the Wardens were fighting off a demonic invasion. She than informs us that Mae was here a short two weeks prior, she was done with her hunt and perhaps became the prey. The Great Trees are not merely the sacred dwellings of the elves, the elves inhabited the great trees in order to serve as protectors.

We head to Pinochle's house which has a 150 tall door, she takes Dawn for a walk, they see Myrtle and Ieyagi. Pinochle informs Dawn that Ieyagi and Myrtle, while not as old as the two creator beings, are older than the rest of the gods. However, the nature beings worked for an entity before Myrtle and Ieyagi became their caregivers.

We go to sleep and head off in the morning. Before we leave Pinochle informs us that she is uncertain about the value of Ieyagi's neutrality in this competition. If need be, she would rather have us destroy her and take her boon than another god's champion.

Far Stone Mine

We take our leave and head to the Far Stone Mine,. On our way we run into a bard, his lute only has two strings. We attempt to restring the lute and have him play, it is not good, and we are not good at lying about it. The foreman tells us that his five miners went down a few days ago and haven't resurfaced. We get four mine carts and go flying down the mine shaft, it is effectively a roller coaster. We reach a three way split in the tunnel. One is for iron, another for gold, and finally a tunnel for hearthstone, we head down the hearthstone tunnel.

On our way down the tunnel we come across several derailed mine carts , we get out and start walking. We send Dawn ahead and she sees in the room at the end of the tunnel. In the room there is a dead dwarf, a mage with a red stone, several lizard folk, a troll, and a zombie. The dwarves Scott, Eugine, Derrick, and Gunther are in the corner crying out for their lost comrade Carl.

We begin the combat which is a ton of fun. It becomes considerably easier once Dawn is able to free the dwarves. Once they are out they tunnel into the wall and once a turn we are able to call one of them in to perform a lair action. Long story short, it was yet another incredibly fun combat.

At the end of the battle the mine starts to collapse in, we grab the largely spent hearthstone the mage was using and a few other things. We start a fairly short chase scene with the dwarves mining, we get a hearthstone and some gold. We finally end the chase and the session when the dwarves mine into a room with a marble statue of a knight kneeling with its head bowed.