---
title: "Session 2"
format: html
---

I, Roland, was not at the beginning of the session due to a schedule conflict. When Ryean woke up he immediately left to retrieve his fathers hammer. A new player character was introduced, a fairy spell caster. Selscior and I were in a deep slumber after the events of the past day and a half.

Mess Hall

When Roland wakes he goes to the gates and attempts to leave to grab Ryean's hammer. There he learns he needs permission from the guard captain and an escort, it does not matter since he is informed the hammer had been retrieved. Roland also hears of an elderly knight that has been living in the fort and doing chores for sometime now and that Roland should meet this man, Guntz.

Then Roland makes his way to the mess-hall, Ryean pushes past him apparently grabbing herbs to make the fort's food worth eating. He starts placing food on his plate and spots Lutin stuffing his face full of different meats with tears of joy rolling down his face. Roland is almost done with his food when a massive figure exits the stairs and leaves the hall, matching the description of Guntz. He follows the man and sees this strange creature using his tongue to eat.

The Paladins

Roland inquires the create as to if it is this Guntz fellow. The creature responds in the affirmative and when prompted tells Roland of an ancient order of knights that has long since died out. This order was named The Warden's which fled to Ostergaia, after a great evil took power, from their native homeland. The order continued to fight evil in the Great War but their King died. Without a leader they gradually separated, died, and passed into myth. The great paladins were buried under cairns, in sepulchers, tombs, and shallow graves. They were buried with The Tenant's, artifacts wielded by the Wardens, only when recombined will the order be reformed.

We spent the next few days training with our respective mentors and gained feats. During this time the captain of the guard from Daus was scouting and investigating Hamiltown.

Accusations

The captain, Verios, returned after several days with news that outskirts village was intact and the city was in perfect condition but everyone was missing. Verios accused us of being spies. He says that the villagers claimed the townsfolk attacked the village. Verios slipped and said that the villagers were human, something that should have been obviously fishy. He continued to press us until the Lord of Fort Daus stepped in and stopped Verios.

After some discussion we decided that we would head to the outskirts village the next day with Mae, a scout from Daus. Verios would hunt down the invaders. Mae would keep an eye on us and be the official reporter for the mission once we returned. Once this plan was set, Roland started to ponder all that he knew and formed a theory. Roland went to the Lord of the Fort and asked about Verios. The Lord was apologetic for Verios' behavior and said that Verios has challenged his leadership of the Fort.