---
title: "index"
format: html
---

We have found out to do jobs for the city we must notify the Bailiff before payment. The party heads over to the bailiff, we decide to deal with the cities rat problems before the siege, no one ever selects this quest so it should be interesting though it is only for thirty gold total. The bailiff is quite helpful in offering us wax plugs for our nostrils, sewers and all that. We are informed that the rats are centered our the church and Hammerhall forge.

We head for the church first, moving a small trap door, Ryean leaps to the sewer below, everyone else opts to climb down the ladder. Lutin casts light on Butch and Selscior scans the tunnel, keeping an eye out for anything suspicious, he mostly sees rat bones. We start to sense something is off and Lutin chucks Butch down the tunnel glimpsing a swarm of rats. Thankfully rats are not the most observant and we are able to get the jump on them.

The rats spread out, one bites Roland manages of paralyze him for several rounds, large bats also join the fray. After a surprisingly damaging battle, both Roland and Lutin dropping below half. We surface back into the church and take a short rest. Lutin also splits up the wings, keeping one and giving Selscior the other.

The Giant Rat that Makes All of the Rules

With that we headed to the smithy, again Ryean leapt into the sewer with the rest of us climbing down. Selscior leads the party down the tunnel. We finally arrived at the sister where the three main tunnels collected, we jumped down. On the far end we see a halfling in tattered clothes, muttering "rats, rats, rats" to himself. The party stops to discuss if we should attempt to talk to him. The halfling scratches his head with a foot, Selscior sneaks to his right. We decide to approach the man to try to talk to him, he sees us he screams "RATS!!!" we roll for initiative, he turns into a wererat.

Ryean immediately crits twice and kills a summoned rat, Lutin smites another rat. The self-appointed Rat King leaps into the muck sinking below the muck and emerges slashing at Lutin. Selscior casts hold person allowing Lutin to deal 69 damage and us to stack up the double damage. After an interesting combat all the rats flew and we head over to his tent.

Its tent is made of rat pelts, sewn together with sinew, his pot and spoon is made of bone, his one possession is a wooden desk. It has a book made of rat leather, written with sewer sludge. There are several pages of "rat, rat, rat", a few more about how much he likes rats, a few more about disliking rats, and lastly a confession of sorts.

The Rat Lord was from beggar camp, he stole a pendant from aristocracy and was caught. He ran away and escaped into the sewers. In a desk drawer is a golden pendant with a drawing of the family. Roland studies the drawing to recognize these people. In the back corner there is a stack of around a dozen bags of grain that we prestidigitation and surface with us.

A Suspicious Bard

On the way to the Bailiffs quarters I see another group of orcs I recognize from Outskirts, I nod my head their way. We give the Bailiff the pendant, he informs us it is from the Karth family, they are fans of the lord. We decide we will next go along the river to collect herbs, delve into the forest to find the garden of Mae's friend, and get back within the next week. Lutin, Ryean, and Dawn all head to Hammerhall to discuss a job they need done while Selscior and Roland head to the library. Apparently they are having issues getting ore from nearby mines, we need to head East to check out the mine. Selscior is able to convince the front desk to let Roland tag along as his body guard.

Selscior starts looking into the history of the Elves, he finds a twenty-four volume set. Volume fifteen discusses the Great War. Apparently pre-Integration the Orcs and the Elves were the two predominant races and were able to coexist. After the appearance of humans and the Great Integration, the humans chopped and burned the forests of the elves. There is only one tree known to the world and it is within Bleakwoods. The book speculates there is a second, subterranean tree and elven civilization under the Tundra. He also does some research on the genealogy of the rulers of Altafaier.

A Curious Paladin

Roland begins with researching the reign of Castillo starting with general information about his family. In his autobiography "The Brilliant Mind of Castillo" I find out all of Borgeniss was once under control of Norgrain. He had two brothers, both younger, the older of the two left Borgeniss for the Greygard Mountains and joined a monastery. Later in life he returned to southern Norgrain started a farm and a family. The youngest brother died about forty years ago in a naval accident, his body was never recovered and was presumed dead. All he says about his removal from his title is that he was forced out by the other lords and that the only heir was his nephew Brauchuss. Roland also looks into the laws regarding libraries and colleges seeing what the punishment would be for infiltrating the college.

With all that we head to the Goldentide Inn, Selscior plays and gets fifteen gold in tips and free lodging. We each have quite visceral dreams in which we get taunted by a women with silver eyes. We are able to deduce this is the champion of the Moon Goddess Zephene. It would seem Selscior and his father had a poor run in with the law in Altafaier.