---
title: "Session 1"
format: html
---

We began the session with each player introducing their character and then having a one-on-one interaction with the festival before the group began to assemble.

The first character, Ryean, a dwarf baker opened the session in his bakery getting the last few loaves ready for the festival. Next was Roland, a half-orc fishmonger, who while on his way to Hamiltown from the Outskirts Village saw children making model ships. Following Roland was Selscior a half-elf entertainer who played a carnival game or two. Finally was Lutin, a dwarf butcher, he started in the shop with his father before going out to the festival to play games.

Following the initial introductions Ryean went around the festival as an OSHA of sorts, trying to make the games safer, meanwhile the characters one by one joined him. We played a few games together, including a fairly quick game during which Roland won a feather of pure gold. Roland intends to make the obviously magical feather a necklace to keep rather than to use.

The Plot Thickens

During one of the games Roland and Selscior spotted three people sneaking into the moat around the lords castle. Roland and Selscior overhear the men talking about how they will use the sewage tunnels as an escape route. The to be Paladin and Bard enter the moat and question the men who say they are there to clean the moat. While this seems semi-plausible and perhaps they misheard, but earlier Ryean had mentioned the cleaning of the sewage tunnels/moat happens annually. They also reason that the cleaning would happen before the festival, not during. So, the two decide to bring it to Ryean's attention, after a brief discussion they inform the bailiff.

With that issue dealt with the party resumes the games. Following a particularly ruckus game involving a water mill, the party went back into the village for to finish a few small tasks. Roland stand there in the middle of the village, a place he normally is not comfortable being and swells with pride and determination. The leader of Selscior's group expresses his desire that Selscior leave the group for a time and discover the world himself. Lutin goes to the church and discusses ways to solve his meat allergy and hashes his bet, going with all three.

The group reassembles and joins a growing crowd, the final event is about to happen. The entire village gets in a line and in groups of four places a sacrifice of sorts in the fire. The party is called forward and one by one they place an object in the fire. Ryean places a loaf of bread, Newt places a piece of meat, Selscior places SOMETHING, and finally Roland places his quarter staff. A massive cloud envelopes the group and they are transported in front of sixteen very angry gods. Myrtle has selected us four as her champions, it is us four that the future will pivot upon.

Time to Run

The four of us come back, no time has passed, we remove ourselves and briefly discuss what this means. Before we know it we are thrown into a massive parade going around the town. A man is spotted on a hill, his shadow thrown in the evening light. He is wearing a horned helmet with a sword in one hand and a pick-axe in the other. He commands his emerging force to charge the village. The group splits, Ryean running for his house. Selscior into a random house to loot, Newt to his house, and Roland stays outside.

Ryean starts shouting for his brother and father to quickly get outside. Ryean starts gathering things, he doesn't hear anyone moving so goes into his fathers room. Over his father Ryean sees his brother weeping, on the bedside table is a half empty bottle. Ryean grabs his brother and gets him out while questioning him.

Selscior quickly discovers he is in Rose's house and gets Rose and her grandmother out of the house. Lutin enters his house to see his father gearing up and Lutin grabs his meat cleaver. Everyone exits the houses and start running for the sewage tunnels in the moat they learned about earlier that day.

When they enter the moat they spot the Bailiff face down in the muck, one by one the group and villagers slide down the tunnel. Ryean runs to hold the hatch open for Grandma, Rose, Selscior, then Lutin. Lutin's father stands by the Bailiffs body readying his final stand, Roland decides to stand with Lutin's father and goes for the Bailiffs sword. When Roland reaches down he discovers the Bailiff if alive, if only just and the mission instantly changes. Roland hoists the Bailiff across his back and dashes for the hatch. Lutin's father runs the other way dragging the enemy attention.

To be Heroes

When the party exits the other side of the tunnel they discover the three ruffians. There the characters when pressed to the edge gain their levels. After everything they have gone through this day, they will not accept their fate. They gain three levels, Ryean rushes in and starts hacking at a ruffian. Lutin enters the fray bisecting one of the men. Selscior attacks one and Roland positions himself to protect the civilians and restores the Bailiff. Ryean kills the ruffian and the third is quickly knocked out. The party reigns in three horses from the nearby stables. We then prop the ruffians bodies up and slap the horses in a different direction. The group now heads to the forest towards Fort Daus.

The party decides to lead a forced march to the fort hoping to out pace and out distance the invading savages. They spot a man they believe to be Lutin's father being dragged behind a horse back towards the village. Rose's grandmother starts to tire quickly and the party starts taking shifts carrying her. There are a few scares but by the morning the group can see Fort Daus. They decide they will try to sneak but the enemy spot them, the chase is on.

An advance group of three cavalry start chasing them quickly closing the gab. Roland manages to should the grandmother for sixty feet. Ryean throws his fathers hammer dismounting one of the cavalry. Selscior guides the civilians and Lutin engages another of the cavalry. Roland manages to place the grandmother on the horse of the dismounted soldier and is able to guide it to the fort in short order followed by other civilians and Selscior. Lutin and Ryean continue to slow the cavalry but get caught in a volley from the fort. After another exchange of blows including Lutin bisecting another man the forts cavalry ride out to meet the enemy with Ryean and Lutin safely getting into the fort.

Once in the fort Ryean retells the previous days events to the captain of the guard at the fort. Roland mentions the commanding officer who was so confident he didn't even bother joining the fray. During their forced march to the Fort the group spotted others running to the forest for refuge and some even running to the mines. Ryean talks to Rose about his actions the past few hours and Ryean confronts Lutin on his murderous actions. During the night Lutin has three dreams, one for each of his benefactors. Roland leaves the fort early in the morning to try and find Ryean's hammer.