---
title: "index"
format: html
---

This was our first online session during winter break, I was somewhat late to the session and Selscior was

When the party wakes we watch as the circus equipment dissolves and blows away into nothingness. The people that had been kidnapped start to wake and we start going through the crowd looking for the mayors grandson. We spot a barrel shaking slight and we start talking to the kid, he doesn’t want to leave the barrel, so Ryean crits the barrel spiting it open.

We walk back to the manor with Hurk, Mr. Heskin is glad to see is his grandson is alright and awards us 500 gold pieces. He also informs us the Norgrain is sending two squads of knights to help the town, they are going to throw a party for the Heroes of Hamiltown. We thank him and inform him it would we really should be on our way.

We head south out of Simpletis, while crossing the river we hear a voice telling us to bath the wings in the water and we all enter the river. Lutin temporarily dawns both wings. We start sinking until we are ripped out of our bodies and thrown along the river to the northwest and see a pound with a shrine of myrtle, we fall down a waterfall, and see the mouth of a cave, within the cave is the statue of a knight.

We regain consciousness and see the knights riding into Simpletis, since we are curious we send Dawnsbloom into eavesdrop. Various would seem to leading the contingent and tells Heskin that we are needed by Lord Brauchuss, we are skeptical and head to the cave.

We start to feel a great shaking of the earth then start to hear the stomps of feet and a mixture of creaking and cracking. It gets louder until we begin passing animated trees. Dawn decides she is going to be brave and talks to it, all it says is “We march west. Lush forest west. Fresh sea salt wind west.”

As we make our way with our wagon we come across a tree in the road, we all know whats up. We get out and start to try to clear the road when six bandits appear and attempt to intimidate us. We glance each others way, nod our heads, and chuck the tree at the charmer. He is not dead, but everyone takes a good step back, it seems like he won’t be getting up anytime soon.

Hello, this is the author here, I have made the executive decision to play the game during combats, it really doesn’t work if people aren’t thinking ahead. As such, I will have very few notes on combats.

From the shadows a man wearing a tusked helmet with a pickax in his hand steps forward calling the others useless, a very cool boss fight ensues. First Roland goes down, within short order Dawn and Lutin are felled until it is just the Champion of War and Ryean standing. The Champion offers Ryean a deal, he can die heroically or the party can Rocky our ways to the top to give him a more enjoyable fight. Ryean chooses to fight another day, neither is particularly overjoyed with this.

The Champion leaves and Sir Various catches up to us informing us that Mae sent a letter back and we are required for the reading of it in the Lords court. Ryean makes them knock him out, it takes the two guards a good while to subdue the barbarian.