---
title: "index"
format: html
---

A Restful Sleep

The session began with Dawn watching Qolbis, Goddess of the Sea, arguing with Myrtle. She is accusing Myrtle of unfairly interfering with game of the gods. They tentatively agree to keep their cooperation and Dawn's being part of the party secret. We also find out that fairies are the servants of Myrtle which were mostly wiped out.

Shelter

When we wake we start to head south during which we lose our way and run into a curious tree. As it turns out this is the house of three haflings, Peter, Roger, and Duff, they had been chased out of Levenfoul because they supposedly cheated while gambling. They have setup shop in this three which has been partially hollowed and filled with the small carvings. They inform us that they buried their winnings somewhere in the forest and they have no need for it, they also point us in the correct direction.

The trip southward is soured somewhat when it starts storming heavily, we decide to take a break and seek shelter in a cave. In the cave is a small stream and a pond. While we get a fire going we start to hear a faint knocking and Lutin starts looking around the cave. He is able to find some faint etchings in the rock face, Lutin and Ryean use their dwarven abilities to identify that the door is slate, different from the rest of the cave. Ryean gets his war hammer out and knocks the door down, we enter leaving the cracked Artur behind.

The Entrance

In the inside is a large marble statue of a knight with a shield, his head looking towards the ground. At the base of the statue are offerings, in the corner is a small kobold wearing a skull helmet wielding a femur, his name is Knots. The base of the statue also has a plaque which seems to be in primordial and among the offerings are papers in celestial, deep speech, and infernal. After we read a letter in celestial we catch the word "steadfast" and say it at the door which opens up. As we make our way down we make sure to get rubbings of the etched runes.

When the door lowers Knots down down the hallway, the walls of which are covered by a mural depicting the arrival of the Wardens. We also we the insignia of the Wardens

The Iron Crown

The party enters a room in the center of which is a table with an ancient feast laid out and a skeleton at the end of the table wearing an iron crown, it lifts its goblets to us. We approach the skeleton and the wall panels open up with draugr stepping out, Ryean and Lutin to the north of the table, Selcior and Roland to the south and Dawn to the West. Roland is able to turn the three closest draugr, functionally removing them from the combat and wraps around the Eastern edge of the table passing the Skeleton.

With Ryean, Lutin, and Roland up close bashing away, Selcior aiding our attacks, and Dawn spell slinging we make short work of the three draugr to the north. Roland heads towards the south, the Skeleton looks towards Roland and says something in primordial, to start on the draugr over there and yells for Selcior to remove the Iron Crown from the head of the Skeleton. Selcior is able to remove the Iron Crown using mage hand placing it in his bag and succeeds in his DM roll, Selscior receives the Game Masters Crown and the Skeleton falls apart.

With that we quickly dispatch the remaining draugr and lift the cover of a particularly ornate looking dish, under which is Bread of Life Ryean consumes it. We do a brief search of the room, getting a rubbing of the doorway, we collect 100 gold pieces and Roland grabs a pauldron of one of the Draugr.

Between a rock and a wet place

In the next room are two massive stone blocks, an exit, and a turn crank in the center of the room. Ryean, Roland, and Lutin take up positions and start twisting the crank. Roland gets a natural 20 for strength lifting the blocks. Ryean then gets a natural 20 on constitution for keeping our progress, the blocks start to rise open the door, and water starts pouring from the ceiling so Knots, Dawn, and Selcior depart. Lutin rolls a natural 20 for turning the crank.

With that Roland and Lutin dive away from the crank getting bellow the door for which Ryean rolls another natural 20 for constitution holding the blocks and door in position. Roland and Lutin hold the door for Ryean to dive through. Roland leaps out from the door early and Ryean leaps in holding the door up. Both Ryean and Lutin are able to jump out at the same time.

Light Weaponry

The hallway is lined with torches and splits part of the way, we head left. That room is partially filled with water and a raised track, on the far end is a tree. Lutin grabs a lance and jumps across to the track and a horse appears and the Treant animates. Lutin wins one bout and loses the other, same with Roland. Ryean is able to knock the Treant into the water. We make our way across the room to the iron gate which opens for us.

We enter an armory, the weapons are entirely decayed, we find ten gold pieces each, and a chest in the back. The party doesn't have a key so says "steadfast" which pops the chest open. Lutin reaches in and grabs a buckler he hands it to Roland and it turns into a heater. Along the top of the shield is primordial script and the insignia of the Wardens in the center.

In the next room we find Knots, who went right. There are six pillar, three on each side and facing us is a suit of armor. Knots pokes The armor which doesn't respond, we say "steadfast" and the armor instantly slices through Knots. Roland rushes to Knots pouring some health from his pool to Knots and initiative is rolled. Selscior forces it to flee from him and Roland gets 33 points of damage from the attack of opportunity. Between the five of us, we defeat it with relative ease.

The Sepulcher

Through the doorway lies a sarcophagus which we pivot open, on the inside are the remains of Sir Claudius. He is clutching a silver pendant and a stone slab which has a quadrant of the Wardens Tenants. After asking for permission, to which we get a response, we grab the silver pendant and stones. The Amulet of Sir Claudius and Gemstones of Power to the Mighty Caliburn, an ancient sword of great power.

We shift the sarcophagus and everyone except Roland go down a flight of stairs at the bottom of which is a gemstone. The gemstone is restrained by four chains, Lutin slashes through them, each time causing the earth to shake in fear. Once free the gemstone flies into Butcher, Lutin's blade, which adds a hook.

We exit the Tomb of Sir Claudius and find a pile of trinkets and a note from Knots. We follow his directions and run into a camp with Trevor and a female ranger, also from the last game of the gods. She warns us against the Wardens, they fell to their own folly, bringing the evil of the old world here.

We reach the edge of the forest, to the east of a massive camp with a short wooden wall, to the west is the town Simpletus. We head to the town which has a massive circus tent, two inns Selcior, Dawn, and Roland head to Sylvian Lullaby, Ryean and Lutin head to Rocken-stone.