---
title: "index"
format: html
---

After our nightmares we wake up and head over to the Bailiff. On our way we see that the friend of Gesik is no longer in the stocks. We also notice that the beggers are inching closer to market square, we each give out nine gold, though money is not the primary issue. Apparently even Castillo ventured out here and talked to Gesik. The main issue now is shelter, while out we need to find a lumber mill and get lumber. During the conversation, Lutin sees the orc group from Outskirts, they are missing a member.

We continue on our way to the Bailiffs quarters and knock on the door, waking him up. When he finally opens the door we just say we’re headed for the forest and start walking away. Selscior requests we get the Game Masters Crown identified further so we head for the church. We talk to Father Varilio, he tells us to seek out Tristram, he is a tailor that trained at the college and worked on magical thread.

Apparently such crowns were somewhat common at parties, the magic can be somewhat altered depending on the situation. While you can direct the enchantment, generally letting the magic chose its form will wield the strongest results. This does come at the obvious risk of not knowing what the enchantment will be. Such magical artifacts are quite common among bards, loosening their tongues allowing for wittier responses. Selscior decides to go the quick and dirt route allowing Tristram to let the magic snap to whatever form it may. We offer Tristram gold but he refuses, saying the opportunity to work on such an artifact makes up for any cost. He does sell several of us on infinitely repairing, always fitting clothes made of magical thread, fifteen gold each.

Encounters of the Fifth Kind

With our business in town at a conclusion we headed to the cart and left town. On our way we see a large stone building, it would seem Norgrain is in the midst of training up its garrison. We also see a butcher’s shop run by a Firbolg, it is a very clean operation. The Firbolg bemoans the response people generally have towards butchers “Go into a town with a butchers blade and everyone thinks you’re crazy.” Lutin gets a few chunks of warthog and a meat sack. Next we run into a group of fisherman, we stop and try our hand at catching a massive catfish though none of us succeed. Lutin attempted to use eldritch bolt with help, a 2 then a 3, he then used his inspiration and rolled another 3. Dawn does win a rock throwing contest and gets some gold.

As we continue on our way we collected five bellalichen. We run into a pond with the monk from the previous Game of the Gods meditating on a rock in the center. There is a storm brewing, the waves of the pond seem to be in sync with her heartbeat. We decide it is best to leave her and her gear (near a shrine to Qolbis) alone.

At last we enter the basin Rose spoke of, we can hear the cries of Weeper-reeds. There is a small stream with a bridge running across it at the mouth of which is a group of goblins. The goblins are dancing around a central figure distinctively dressed. When we approach, the goblins secret service style push the figure to the back of the pack. During our conversation we notice they are generally fixated on us and not the cart so Dawn gets the cart rolling. Selscior gets what Dawn is doing and gets out his flute and gets a 29 in performance with Ryean joining in a dance. Lutin notices the stream is really small and literally walks across it not using the bridge. We realize the bridge is just here and does absolutely nothing so we also step across it. The goblins, dejected, saunter off, the leader casting his distinctive clothes aside. We are able to collect five Wheeper-reeds.

The Full Moon

We decide to rest for the night. Lutin gives Roland the fish from his bag, I roll at dirty 20 on filleting them, I’m able to collect a vial of fish oil. Dawn decides to take solo watch throughout the night. As the night wears on a figure appeared from the shadows magically putting Dawn to sleep, though Dawn can see through the dream somewhat. She sees a small figure laying in a pool of water crying.

The entire party fails our wisdom rolls. Lutin is able to pull Butch out and strikes out at the inky moon. We wake up, Lutin sees his blade is wet with blood, he casts hex on the figure, we roll initiative. She summons two shadow figures and an incredibly intense battle occurred. Roland was downed twice, Lutin and Selscior once each, even Ryean was reduced well below half before getting healed. We finally defeated her, a cloak, her body. Our respective primary weapon become moontouched.

When she is defeated she turns into her true form, a small tiefling child, neck snapped. Ryean, who dealt the final blow, storms into the forest, yells at the moon, Zephene appears, he has a tense conversation with her. Zephene was created by the Wardens, forced into godhood somehow. Zephene is a tired god and wishes to be done, we will seek the conclusion of Zephene. Lutin calls out to Butch but a new voice answers. This new voice is the added gem, a separate aspect of Butch. It claims there were two gods, one of them was split apart and cast about the world, this is Butch. Lutin believes the other was similarly split up, but instead infused into the life of Ostergaia.