---
title: "index"
format: html
---

We begin the morning by finding out that Myrtle is dead. Dawnsbloom does not function and just throws pebbles at Lutin. Rose shows up at the house and talks to Ryean. After a fairly extensive conversation Rose says she will not interfere with fights with other champions. She also lets us know she has a job for us. We decide we will do the Grey Keep job first so head to the Bailiffs Quarters. We all knock on the door and he chooses to slide the contract under the door. With contract in hand we head to the shop and get the cargo train moving to Fort Dauss.

On Guard

Along the way, Lutin notices that one of the fields has a pattern to it. Once we are aware of it, it is obvious, the field has been shaped in the symbol of Kyios. In the middle of the field is a shrine, we continue on our way and see even more blight than yesterday. Later a tornado of leaves hits Dawn who follows it to a small garden of herbs, five of each.

About halfway to Fort Dauss Lutin spots a snare head in the road, we stop to disarm it. When we stop bandits start pouring out of the surrounding brambles, they are Carrion Crows. After a fairly quick combat, ending with Lutin executing a captured bandit, Lutin's father steps from the bushes. A very intense conversation takes place. It would seem that he has some connection to the Wardens and that is why he had Butch. He tells Lutin that the next time we go to a tomb he should see what his blood does, whatever that means. He departs after effectively promising the next time they meet only one of them will be walking away. Ryean also extorts some money from Casandra for not joining the fight and being out of practice. When we reach Fort Dauss it is clear they have been hard at work overnight. We talk to Various who gives us fifteen gold pieces each.

Dirty Business

We then decide to do the quest for a merchant in Norgrain. The post said a wagon had left Ratheios but didn't arrive, it has something of his. He does not specify; however, it will apparently be clear what it is. We head towards Ratheios for some time. On our way we run into a mercenary that has been hard at work. We find the wagon tipped over and tracks headed North of North East. Following the tracks we find a dead tree that has many people hanging from it. There is a sign in primordial that reads "As always to our oppressors". The people have symbols of both Norgrain and Ratheios, some even have the mark of the Wardens. Selscior draws the scene sending a raven back to Norgrain with the sketch.

The trail ends at a set of ruined stone buildings. Selscior uses his familiar to scout the rubble finding a small troupe around a fire. After talking we devise a plan, Selscior and Dawn will hang out of sight while Ryean, Roland, and Lutin barge in. Ryean breaks through the wall entering the camp followed by lutin and a ducking Roland. The people offer us a place to sleep, they seem quite nice, we strike up conversation. Dawn goes invisible, spots the lock box, sneaks into it, loots it, and misty steps back to Selscior who messages the group. Roland stands up and acts as if he just remembered he left the stove on in Norgrain, they really should be headed back asap. As it turns out Dawn stole everything, not just the pink glowing Hearthstone so we book it out of there.

On our way back we decide we are somewhat curious about the fight that happened. We follow the path of destructing leading south of the wagon for about an hour before we decide it probably isn't worth it. We end the session headed back to Norgrain with our loot in hand.