---
title: "index"
format: html
---

In the entry is a marble statue of Sir Kirin the Hound, there is a healthy amount of primordial throughout the room. This entrance seemed to have been sealed for quite some time as there are no offerings. After reading a piece of writing we determine that the keyword is "loyal". Once we open the door, we enter the hallway in which is a mural depicting the King of the Wardens surrounded by his men.

The dining room has a single chalice and several suits of armor along the wall. Inside the chalice is a reddish purple liquid which Lutin drinks as combat begins. After defeating the suits we move into the next room in which there is a chain that when Ryean pulls starts to open a seem in the wall. Dripping down the chain is an acidic liquid that gradually starts hurting Ryean. We head into the opening in the wall, there are two jumps onto rolling cylinders. On the other side of the gap is a platform with four bowls. We deduce that four of us must make it across to solve the puzzle and get through. Roland has considerable trouble with this task, falling several times. Eventually we are able to get onto the platform and move into the next section.

Sir Kirin

This hallway splits two ways, one to the right labeled "shrine" and to the left "grave". We decide to go to the shrine first. An ent blocks the way to the shrine and says, "You must match the wit of Sir Kirin in his favorite pastime, riddles." We must solve four of the five riddles, we get all five. On the inside there are a few magic items and Selscior takes the time to cast find familiar.

We then head towards the grave, guarding it is another suit of armor. Dawnsbloom recreates the pose of the statue of Sir Kirin, the suit of armor takes her dart and steps aside. In Sir Kirin's tomb is another Tenant, the Tenant of Loyalty, he has an insignia ring, and the pommel of Caliburn. Lutin pushes the sepulcher to the side and descends into a small room. The rest of the party shares concerned looks and descends after him. Ryean restrains him, Roland steps between Lutin and the gemstone. Selscior tries to use his familiar but it is destroyed by Lutin. Ryean starts carrying Lutin up the stairs before Butch blasts us all away and cuts the chains away. It is clear to us that Butch had been possessing Lutin.

Quite Travels

We quietly head back towards Norgrain, we find nine patches of Bellalichen. Then we run into a very drunk Trevor who then gets Lutin and Dawnsbloom very drunk. We are almost back when we stop the cart to collect four more reaper weeds and hear in our minds a "ribbet" after stopping the cart we have a brief talk with a massive toad Garganell. We finish the session back in Norgrain, it is clear tonight will be mostly restless.