---
title: "Woodworking"
format: html
---

I have spent a fair amount of my life, as anyone that is one of half a dozen children has, doing general contract work for my parents, plaster and lathe or drywall repair; painting; running wires; general construction/carpentry stuff; but the one I do actually find enjoyable, it woodworking. I grew up helping my dad machine lumber with the jointer planer and jointer; cutting boards down to final dimensions with the table, miter, or radial arm saws; and finishing with rabits, pockets, etc... 

In high school I made a truly terrible Tak, of Wise Man Fears fame, game board.

During the winter of 2022, I made several dice trays for the Clash of Crowns crew. 

In the Summer of 2024, I made an overly complex (yet not complex enough, I have ideas for a mark two) coffee bar shelf. 

In the winter of 2024, I made a very nice bookshelf for my girlfriend, though she has started to try to use her Kindle and library access more, which is good, but does mean we have a fair bit of extra shelf space

In the future I hope to make a silly bookshelf for my Drizzt Saga Mass Media Paperbacks