---
title: "Session 3"
format: html
---

After a short hiatus we are back and ready to pickup where we left.

To Hamiltown

We wake up and get ready to leave for Hamiltown. Many of the guards are there to see us off and we meet Mae who will be watching/helping us. The chef even gives us each a loaf of bread as thanks for the baking tips from Ryan.

Along the way we meet a Satyr druid who is obviously extremely powerful and loosing grasp of reality. He gives each of us a berry with a magical random magical effect. We put together that he is from the previous group of adventurers that were selected for the Game of the Gods.

Shortly following that we ran along a stream that went to an alter to Myrtle. It was in disrepair and we did our best job of restoring it and heard her say "Steadfast".

The Vultures

At midday we reached the forest edge. There we can see that the outskirts village is in ruins and looters are in the town. Mae is able to lead most of the looters, a gang call the vultures, away from town. Six vultures remained and we quickly handled them incapacitating the majority, killing a few.

We recognize one of those incapacitated missing a leg as Artur, the jokester from the water mill. Roland removes the insignias from the vultures' cloaks as proof of the groups work. Roland also grabs a dagger and each member of the group collected ten gold pieces worth of items. Mae reappears from the forest after loosing them.

The Conspiracy

We moved onto the bailey. Ryean threw the fairy onto the parapets who then destroyed the draw bridge mechanism lowering it. The party entered, it appeared that the bailey had not been seized what-so-ever. We enter the keep and go down to the cellars, there are three cells and under a bear skin rug a tunnel. The group then went upstairs to Sir Novascoshek's chambers.

Instantly Roland started looking for correspondences, all he finds are standard letters. The party turns the chambers over and finds a hidden drawer with a sealed letter. Selscior being the one to find it attempts to pocket the letter, when noticed he simply reads it in the open for others to read.

For the explanation, I will create a separate post that contains the logic Roland is operating with. Here is the bottom line of the conspiracy. Sir Novascoshek was working with Lord Castillo and Verios to destabilize the balance of power and take control of Borgeniss. We leave the keep via the tunnel and see that Sir Novascoshek in the end stood true to his station and attempted to protect the outskirts village.

Investigation

Lutin finds and repairs Sir Novascoshek's stamp and Roland takes an insignia from a knight's cape. We then go to the moat around the keep and in the same tunnel as the pit we find the bodies of all those that died. Ryean grabs his fathers body which was towards the top. We go back to the town center to check on the people that are tied up. After a brief discussion we decide to investigate the wizards tower to the north of the town.

When we arrive at the tower Lutin uses his hex blade to break the door down, Ryean and Roland share a look of concern. The party makes their way up the tower, there are no traps or monsters to slow our way. Enter a room with a telescope and a spell book in a language none of us recognize. The telescope is pointed directly at where the invaders appeared. We also find a skeleton, Matias the Mad, on the bed with a ring on one of his fingers. We identify the ring, created by a forge cleric, called "For the Wizard". Finally we find a glass of water and a fresh apple, someone has been here very recently. Ryean tries to call out to the invisible person that may still be in the room that we are friendly but there is no response.

We quite quickly that is was our own stupidity that made the mage fear us and run away without any discussion. We decide it is time to bury Ryean's father and head towards the mine to him a proper burial. When we arrive at the mine Mae says that she is claustrophobic and someone should check on the prisoners. Everyone else makes their way into the mine, we get into the tunnel, reach the elevator and descend.

The Foreman's Cairn

Once in the mine proper Lutin starts leading the way. When we first ran from the town we saw people flee into the mine and we start making our way through mud made from their blood. Lutin decides to scout ahead and sees that a great force of undead is at the bottom of the mine. He starts to make his way back but his chainmail is too loud and the chase begins. I will get the chase rules that we used and make a separate post with the rules written out and explained.

We escape to the elevator, Lutin stays to turn the wench to get everyone up. Roland lowers the elevator and tried twice to get Lutin up but the wench keeps locking up. Finally Ryean pushes Roland to the side and raises the elevator, to slow down the mob Lutin thunderwaved, starting a cave in. We all start running out of the cave and Ryean drops his father, not the burial we wanted for him, but it's the one he'll get. We all get out moments before the mine fully collapses.

Mae

The party starts to make its way towards the town to meet up with Mae. When the group gets to town we see that the people are gone. Since it has been raining, we can see Mae's foot steps leading up to where they were tied up. Leading away from that point is a trail with two sets of footprints, Mae started walking in one of their tracks. Outside of the town they diverge, both south one to the east and the other to the west. We decide to track to the south east, it looks like we wont be going back to Fort Daus anytime soon.